stages:
  - publish

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - cp $DOT_ENV_WATER_API .env
    - docker build -t $TAG_LATEST .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $TAG_LATEST
  only:
    - main
